doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: 'pdo_mysql'
                host: '%your_master_host%'
                port: '%your_master_port%'
                dbname: 'm151_cinema_booking_system'
                user: '%your_master_user%'
                password: '%your_master_password%'
                charset: 'UTF8'
            slave1:
                driver: 'pdo_mysql'
                host: '%your_slave1_host%'
                port: '%your_slave1_port%'
                dbname: 'm151_cinema_booking_system'
                user: '%your_slave1_user%'
                password: '%your_slave1_password%'
                charset: 'UTF8'
            slave2:
                driver: 'pdo_mysql'
                host: '%your_slave2_host%'
                port: '%your_slave2_port%'
                dbname: 'm151_cinema_booking_system'
                user: '%your_slave2_user%'
                password: '%your_slave2_password%'
                charset: 'UTF8'

    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            slave1:
                connection: slave1
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            slave2:
                connection: slave2
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App